# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', '女'), ('man', '男')], max_length=50),
        ),
        migrations.AddField(
            model_name='gtp',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='belong', to='gtpxz.Tag'),
        ),
    ]
