# Generated by Django 2.0.1 on 2018-02-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('man', '男'), ('woman', '女')], max_length=50)),
                ('age', models.IntegerField(default='20')),
                ('memo', models.TextField(default='xxx')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='gtps',
            name='uper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtpxz.Users'),
        ),
    ]
