# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blgtype',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='uper',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='toblg',
        ),
        migrations.RemoveField(
            model_name='gtp',
            name='type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='type',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comaut', to='gtpxz.Profile'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Gtptype',
        ),
        migrations.DeleteModel(
            name='Vidtype',
        ),
    ]
