# Generated by Django 2.0.1 on 2018-03-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0002_auto_20180228_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtps',
            name='CreateDate',
            field=models.DateTimeField(default='2012-1-2 12:00'),
        ),
    ]
