# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0002_auto_20180408_2240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='tag',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='gtp',
            name='tag',
        ),
        migrations.AddField(
            model_name='gtp',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_belong', to='gtpxz.Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', '男'), ('woman', '女')], max_length=50),
        ),
    ]
