# Generated by Django 2.0.1 on 2018-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0003_gtps_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtps',
            name='CreateDate',
        ),
        migrations.AlterField(
            model_name='users',
            name='memo',
            field=models.TextField(),
        ),
    ]
