# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0003_auto_20180430_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uper',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tovid',
        ),
        migrations.AlterField(
            model_name='comment',
            name='CreateDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtpcom', to='gtpxz.Profile'),
        ),
        migrations.AlterField(
            model_name='gtp',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
