# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0004_auto_20180430_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comgtp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', '女'), ('man', '男')], max_length=50),
        ),
    ]
