# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0010_auto_20180502_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtp',
            name='gtp',
            field=models.FileField(blank=True, null=True, upload_to='gtps/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', '女'), ('man', '男')], max_length=50),
        ),
    ]
