# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0012_auto_20180502_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', '女'), ('man', '男')], max_length=50),
        ),
    ]
