# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtpxz', '0002_auto_20180428_1328'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blgcom', to='gtpxz.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='uper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pubblg', to='gtpxz.Profile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, choices=[('second', '技术贴'), ('third', '公告贴'), ('third', '交♂易贴'), ('first', '水一贴')], max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='toblg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reblg', to='blog.Blog'),
        ),
    ]
