# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180430_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, choices=[('first', '水一贴'), ('third', '公告贴'), ('second', '技术贴'), ('third', '交♂易贴')], max_length=50),
        ),
        migrations.AlterField(
            model_name='comblog',
            name='CreateDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
