# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180430_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comblog',
            new_name='Comblg',
        ),
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, choices=[('third', '公告贴'), ('first', '水一贴'), ('third', '交♂易贴'), ('second', '技术贴')], max_length=50),
        ),
    ]
