# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comvide',
            new_name='Comvid',
        ),
    ]
